version: '3.8'
services:
  woo_scraper:
    build:
      context: woo
      dockerfile: Dockerfile 
    container_name: woo_scraper_app
    environment:
      - DB_HOST=192.168.1.17 
      - DB_NAME=Mahdi
      - DB_PASSWORD=password
      - DB_USER=root 
      - CATEGORIES_FILE=woo_stores.json
    networks:
      - app_network
      
  shopify_scraper:
    build:
      context: shopify
      dockerfile: Dockerfile
    container_name: shopify_scraper_app
    environment:
      - DB_HOST=192.168.1.17 
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=web_scrap_db
      - STORES_FILE_PATH_IN_CONTAINER=stores.json 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
