version: '3.8'
services:
  woo_scraper:
    build:
      context: woo
      dockerfile: Dockerfile 
    container_name: woo_scraper_app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}  
      - DB_NAME=${WOO_DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CATEGORIES_FILE=${CATEGORIES_FILE}
    networks:
      - app_network
      
  shopify_scraper:
    build:
      context: shopify
      dockerfile: Dockerfile
    container_name: shopify_scraper_app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${SHOPIFY_DB_NAME}
      - STORES_FILE_PATH_IN_CONTAINER=${STORES_FILE_PATH_IN_CONTAINER}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
